site_name: Awesome MicroPython
site_url: https://awesome-micropython.com
site_description: A curated list of MicroPython libraries, frameworks, software and resources.
site_author: Mike Causer
repo_name: mcauser/awesome-micropython
repo_url: https://github.com/mcauser/awesome-micropython
edit_uri: ''
theme:
  name: material
  language: en
  logo: img/logo_nav.svg
  favicon: img/favicon.ico
  custom_dir: custom_theme/
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: teal
      accent: deep orange
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: deep orange
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
extra_css:
  - css/extra.css
extra:
  analytics:
    provider: google
    property: UA-1390021-18
plugins:
  - include-markdown
  - search
  - awesome-pages
  - minify:
      minify_html: true
      htmlmin_opts:
          remove_comments: true
          remove_optional_attribute_quotes: false
nav:
  - "Awesome MicroPython": "index.md"
