name: Check Links

on:
  push:
    branches: '*'
  pull_request:
    branches:
      - master
  schedule:
    # Runs on the 1st of the month at 9 am
    - cron: '0 9 1 * *'

jobs:
  awesome_bot:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ruby/setup-ruby@v1
      with:
        ruby-version: '3.3'
    - name: Install awesome_bot
      run: gem install awesome_bot
    - name: Load allow list to an env var to call in the next step
      run: echo "BOT_ALLOW_LIST=$(tr '\n' ',' < .github/workflows/allow-list.txt)" >> $GITHUB_ENV
    - name: Run awesome_bot
      run: awesome_bot readme.md --allow-redirect --allow-dupe --set-timeout 60 --skip-save-results --allow 429 --white-list ${{ env.BOT_ALLOW_LIST }}
