name: Publish on GitHub Pages
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Deploy awesome list
    runs-on: ubuntu-latest
    steps:
      - name: Checkout master
        uses: actions/checkout@v4

      - name: Deploy awesome list
        uses: mhausenblas/mkdocs-deploy-gh-pages@master
        env:
          GITHUB_TOKEN: ${{ secrets.PERSONAL_TOKEN }}
          CUSTOM_DOMAIN: awesome-micropython.com
